// Code generated by MockGen. DO NOT EDIT.
// Source: ./captcha.go

// Package mock_captcha is a generated GoMock package.
package mock_captcha

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRandomizer is a mock of Randomizer interface.
type MockRandomizer struct {
	ctrl     *gomock.Controller
	recorder *MockRandomizerMockRecorder
}

// MockRandomizerMockRecorder is the mock recorder for MockRandomizer.
type MockRandomizerMockRecorder struct {
	mock *MockRandomizer
}

// NewMockRandomizer creates a new mock instance.
func NewMockRandomizer(ctrl *gomock.Controller) *MockRandomizer {
	mock := &MockRandomizer{ctrl: ctrl}
	mock.recorder = &MockRandomizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRandomizer) EXPECT() *MockRandomizerMockRecorder {
	return m.recorder
}

// Captcha mocks base method.
func (m *MockRandomizer) Captcha() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Captcha")
	ret0, _ := ret[0].(string)
	return ret0
}

// Captcha indicates an expected call of Captcha.
func (mr *MockRandomizerMockRecorder) Captcha() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Captcha", reflect.TypeOf((*MockRandomizer)(nil).Captcha))
}

// Random mocks base method.
func (m *MockRandomizer) Random() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Random")
	ret0, _ := ret[0].(int)
	return ret0
}

// Random indicates an expected call of Random.
func (mr *MockRandomizerMockRecorder) Random() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Random", reflect.TypeOf((*MockRandomizer)(nil).Random))
}
